---
name: library_dhifan
description: Project Library UKK
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.2 <3.0.0'
dependencies:
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/logo.png
  - img/
  - assets/
